//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuartzMaster.Data.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class QuartzMaster_Data {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QuartzMaster_Data() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuartzMaster.Data.Resources.QuartzMaster.Data", typeof(QuartzMaster_Data).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string DataItemKey {
            get {
                return ResourceManager.GetString("DataItemKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string DataItemValue {
            get {
                return ResourceManager.GetString("DataItemValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string SchedulerDescription {
            get {
                return ResourceManager.GetString("SchedulerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Hostname.
        /// </summary>
        public static string SchedulerHostname {
            get {
                return ResourceManager.GetString("SchedulerHostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance Name.
        /// </summary>
        public static string SchedulerInstanceName {
            get {
                return ResourceManager.GetString("SchedulerInstanceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SchedulerName {
            get {
                return ResourceManager.GetString("SchedulerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar Name.
        /// </summary>
        public static string TriggerCalendarName {
            get {
                return ResourceManager.GetString("TriggerCalendarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRON String.
        /// </summary>
        public static string TriggerCronString {
            get {
                return ResourceManager.GetString("TriggerCronString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string TriggerDescription {
            get {
                return ResourceManager.GetString("TriggerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string TriggerEndDate {
            get {
                return ResourceManager.GetString("TriggerEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Fire Time.
        /// </summary>
        public static string TriggerFinalFireTime {
            get {
                return ResourceManager.GetString("TriggerFinalFireTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string TriggerGroup {
            get {
                return ResourceManager.GetString("TriggerGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Volatile.
        /// </summary>
        public static string TriggerIsVolatile {
            get {
                return ResourceManager.GetString("TriggerIsVolatile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string TriggerName {
            get {
                return ResourceManager.GetString("TriggerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Fire Time.
        /// </summary>
        public static string TriggerNextFireTime {
            get {
                return ResourceManager.GetString("TriggerNextFireTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat Count.
        /// </summary>
        public static string TriggerRepeatCount {
            get {
                return ResourceManager.GetString("TriggerRepeatCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Repeat Interval.
        /// </summary>
        public static string TriggerRepeatInterval {
            get {
                return ResourceManager.GetString("TriggerRepeatInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string TriggerStartDate {
            get {
                return ResourceManager.GetString("TriggerStartDate", resourceCulture);
            }
        }
    }
}
